import localFont from "next/font/local";
import "./globals.css";

const poppinsRegular = localFont({
  src: "./fonts/Poppins-Regular.woff",
  variable: "--font-poppins-regular",
  weight: "100 900",
});

export const metadata = {
  title: "Simply Goods",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppinsRegular.variable}  antialiased`}>{children}</body>
    </html>
  );
}
